Sprint 3
alexvasoff/middle.messenger.praktikum.yandex pull request #3
Opened 2022-10-14 23:42 UTC by alexvasoff

2022-10-15 06:36 UTC, agadoev requested changes
Привет, @alexvasoff 
спасибо за работу
Я все внимательно посмотрел и оставил комментарии в тех местах, которые можно улучшить. Из основного - произошла путаница в реализации классов api и контроллеров, нужно будет с этим разобраться. Так же постарайся поправить все моменты, которые я отметил. Давай разберемся с этим и двинемся дальше

2022-10-15 06:36 UTC, agadoev commented on src/components/input/index.ts
>      }
Действительно ли нужен этот код?

2022-10-15 06:36 UTC, agadoev commented on src/components/input/types.d.ts
>    events?: { blur: () => void; focus: () => void };
Лучше переносить свойства объекта на следующую строку, потому что так будет более читаемо

2022-10-15 06:36 UTC, agadoev commented on src/pages/chat/components/chatList/index.ts
> +  }
1) Этот код (а именно отправка запроса на сервер и обработка ответа), должны находиться в специальном классе, который обычно называют контроллером
2) надо как-то выводить пользователю сообщение об ошибке. Как минимум через ```alert()```, как максимум - сделать компонент snackbar

2022-10-15 06:36 UTC, agadoev commented on src/pages/chat/index.ts
> +const chatApi = new ChatController();
Api !== Controller

Разница в том, что они отвечают за разные вещи. Api отвечает только за http, в нем хранятся url'ы и заголовки запросов. В контроллере хранится логика обработки ответа от api. В контроллере может быть бизнес-логика и например редирект на какую-нибудь страницу ошибки

2022-10-15 06:36 UTC, agadoev commented on src/pages/chat/index.ts
> +  chatList : unknown;
по названию можно понять как минимум то, что тут будет массив

2022-10-15 06:36 UTC, agadoev commented on src/pages/chat/index.ts
> +      console.log('TOKEN_VALUE, USER_ID, CHAT_ID:', TOKEN_VALUE, USER_ID, CHAT_ID);
Отладочные console.log'и полезны при разработке, однако их лучше не держать в репозитории. Они загрязняют консоль и отвлекают внимание твоих коллег и тебя в будущем

2022-10-15 06:36 UTC, agadoev commented on src/pages/chat/index.ts
> +    const socket = new WebSocket(`wss://ya-praktikum.tech/ws/chats/${USER_ID}>/${CHAT_ID}>/${TOKEN_VALUE}>`);
Такие константы как урлы, порты, токены, лучше хранить в config-файлах. Эти значения могут поменяться, а значит их надо отделить от исходного кода. Предлагаю создать файл config.js, в котором будет храниться этот урл

2022-10-15 06:36 UTC, agadoev commented on src/pages/chat/index.ts
> +      newChat.onclick = () => {
Не нужно вручную создавать теги и их как-то комбинировать. Для этого есть компоненты. Все Фреймворки - react, Angular, Vue и тд как раз позволяют разработчикам не комбинировать теги, а вообще абстрагироваться от DOM'a, потому что это упрощает жизнь. Предлагаю создать компонент chat (например), и тут создавать его инстанс

2022-10-15 06:36 UTC, agadoev commented on src/pages/profile/modules/changePassword/types.d.ts
> +  savaChanges: unknown;
Тут скорее всего опечатка
```suggestion
  saveChanges: unknown;
```

2022-10-15 06:36 UTC, agadoev commented on src/pages/profile/modules/main/index.ts
> +  }
```getInfo``` может вернуть ошибку, ее нужно обработать

2022-10-15 06:36 UTC, agadoev commented on src/utils/apiControllers/apiPath.ts
> +  login: 'https://ya-praktikum.tech/api/v2/auth/signin',
Если создашь файл config.js (как я писал в одном из комментариев выше), то каждый из этих урлов можно будет упростить
```suggestion
  login: '/api/v2/auth/signin',
```

2022-10-15 06:36 UTC, agadoev commented on src/pages/profile/modules/main/index.ts
> +      }
Этот код уже есть в функции getFormData

2022-10-15 21:38 UTC, alexvasoff commented on src/pages/profile/modules/changePassword/types.d.ts
> +  savaChanges: unknown;
Опечатка в тексте или "по смыслу"? Этот интерфейс описывает какие Компоненты ожидает внутри себя страница. Что-то вроде именованных слотов. Вместо unknown укажу типы компонентов

2022-10-17 11:21 UTC, agadoev commented on src/pages/profile/modules/changePassword/types.d.ts
> +  savaChanges: unknown;
опечатка в тексте. Вместо save написано sava. Но это лишь мое предположение, может действительно было задумано sava. Во всяком случае это ни в коем случае не критическая ошибка, просто наблюдение

2022-10-17 11:22 UTC, agadoev commented
Привет, @alexvasoff 
Спасибо за правки
Вижу, что все поправлено, поэтому работу принимаю. Удачи в следующем спринте :)

2022-10-19 13:24 UTC, merged