Sprint 4
alexvasoff/middle.messenger.praktikum.yandex pull request #4
Opened 2022-10-20 01:47 UTC by alexvasoff

2022-10-20 19:28 UTC, podlovchenko requested changes
Привет, есть несколько замечаний по работе системы
1. Сообщения в чатах не отправляются
2. Нет валидации в изменении данных профиля

2022-10-20 19:28 UTC, podlovchenko commented on src/router/index.ts
> +  // '/serverError': serverError,
Закомментированный код лучше не оставлять в проекте

2022-10-20 19:28 UTC, podlovchenko commented on src/utils/baseBlock/index.ts
> +  _registerEvents(eventBus: EventBus) {
Для приватных методов не хватает модификатора private

2022-10-20 19:28 UTC, podlovchenko commented on webpack.config.js
> +  }
Можно короче
```suggestion
    config.mode = isProduction ? 'production' : 'development';
```

2022-10-20 19:28 UTC, podlovchenko commented on src/utils/baseBlock/index.ts
>    constructor(tagName = 'div', propsAndChildren: BaseProps = {}) {
Было бы здорово сделать класс Block [дженериком](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников
Пример:
```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2022-10-20 19:28 UTC, podlovchenko commented on src/utils/baseBlock/index.ts
> +    const fragment: HTMLTemplateElement = this._createDocumentElement('template') as unknown as HTMLTemplateElement;
Достаточно одного приведения типа

2022-10-20 19:28 UTC, podlovchenko commented on src/pages/registration/index.ts
> +import {SignUp} from "../../api/types";
Можно настроить alias
https://betterprogramming.pub/the-right-usage-of-aliases-in-webpack-typescript-4418327f47fa
tsconfig.json
```
"baseUrl": "src",
    "paths": {
    "@/*": [
        "*"
    ]
},
webpack.config.js

resolve: {
    extensions: ['.ts', '.js', '.json'],
        alias: {
        '@': path.resolve(__dirname, 'src'),
    }
}
```

2022-10-20 21:43 UTC, alexvasoff commented on src/utils/baseBlock/index.ts
> +  _registerEvents(eventBus: EventBus) {
Добавил модификаторы

2022-10-20 21:44 UTC, alexvasoff commented on webpack.config.js
> +  }
Спасибо, исправил

2022-10-20 21:44 UTC, alexvasoff commented on src/utils/baseBlock/index.ts
> +    const fragment: HTMLTemplateElement = this._createDocumentElement('template') as unknown as HTMLTemplateElement;
точно, спасибо

2022-10-20 21:48 UTC, alexvasoff commented on src/pages/registration/index.ts
> +import {SignUp} from "../../api/types";
Алиса добавил. Вначале изменил все импорты, но начала ругаться mocha на незарезолвенные импорты в компонентах, тк не подхватила алиасы. Попробовал использовать mocha-webpack, но там тоже вылезли красители консоли

2022-10-20 21:48 UTC, alexvasoff commented on src/utils/baseBlock/index.ts
> +    const fragment: HTMLTemplateElement = this._createDocumentElement('template') as unknown as HTMLTemplateElement;
точно, исправил

2022-10-20 21:50 UTC, alexvasoff commented on src/utils/baseBlock/index.ts
>    constructor(tagName = 'div', propsAndChildren: BaseProps = {}) {
ага, уже ощутил это, но сейчас по срокам не успею качественно это исправить, надеюсь это не сильно критично

2022-10-20 21:51 UTC, alexvasoff commented on src/router/index.ts
> +  // '/serverError': serverError,
убрал)

2022-10-21 08:58 UTC, podlovchenko commented
Привет, отправка сообщений так и не работает, а этот пункт есть в чек листе, не могу пока принять работу(
10. Подключена HTTP-часть API чата.
11. Подключена отправка сообщений.

2022-10-21 12:17 UTC, podlovchenko commented
Все еще не работает

2022-10-21 12:21 UTC, alexvasoff commented
> Все еще не работает, сообщения не отправляются

@podlovchenko , какой вариант ожидается? Сейчас если перейти в чат и отправить, то запрос на сервер уходит по websocket'у

2022-10-21 13:06 UTC, podlovchenko commented
Запрос по вебсокету не проходит, ожидается отправка сообщения, отображение истории сообщений

2022-10-21 18:50 UTC, podlovchenko commented
Спасибо за оперативные правки, работу принимаю)

2023-01-22 12:47 UTC, merged